# snmpd.conf — Configuración del agente SNMPv3
# Práctica GP4 - Parte 3

# Puerto 1161 en lugar de 161 — en contenedores Docker los puertos
# por debajo de 1024 requieren privilegios de root que no están disponibles.
# Para consultas desde el manager usar: snmpget ... 10.0.125.3:1161 ...
agentAddress udp:1161,udp6:[::1]:1161

# Usuario SNMPv3
createUser vagrant SHA vagrant1234 AES vagrant1234
rouser vagrant priv

sysLocation    Docker Lab GP4
sysContact     alumno@uah.es
